before_install: 
- sudo apt-get update
- sudo apt-get install cmake libv4l-dev
- wget http://cz.archive.ubuntu.com/ubuntu/pool/universe/libl/liblivemedia/livemedia-utils_2014.01.13-1_amd64.deb
- sudo dpkg -i livemedia-utils_2014.01.13-1_amd64.deb 
language: cpp
compiler:
- gcc
script: 
- cmake . 
- make
- cpack .
